### ISSUE TITLE
Pylon pygraph file examples

### ISSUE THREAD

**Issue by IST-EVA-Support** [IST-EVA-Support/EVA_Show-Case#14]
Dear @Moda-Lin ,
Thank you for these examples for EVA IDE. Unfortunately, none of them work. When I click play button nothing happens in IDE. Here is the output in terminal after I start EVA IDE and then open and play each example one after another:
```
adlink@dyn-163:~$ EVA_IDE 
ad_cameraflir_class_init called ... 
ad_camerahik_class_init called ... 
2021-06-17 23:26:53.326652: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "/home/adlink/adlink/eva/IDE/plugins/python/emailAlert.py", line 7, in <module>
    import smtplib
ModuleNotFoundError: No module named 'smtplib'
Traceback (most recent call last):
  File "/home/adlink/adlink/eva/IDE/plugins/python/voiceAlert.py", line 7, in <module>
    import pyttsx3
ModuleNotFoundError: No module named 'pyttsx3'
New pipeline pipeline0
Add element pylonsrc0 into pipeline pipeline0
Add element videoconvert0 into pipeline pipeline0
Add element xvimagesink1 into pipeline pipeline0
Add element adtsrt1 into pipeline pipeline0
Add element adtransclassifier1 into pipeline pipeline0
Add element adinferdraw0 into pipeline pipeline0
Add element videoconvert13 into pipeline pipeline0
pylonsrc0(src) link videoconvert0(sink) done
videoconvert0(src) link adtsrt1(sink) done
adtsrt1(src) link adtransclassifier1(sink) done
adtransclassifier1(src) link adinferdraw0(sink) done
adinferdraw0(src) link videoconvert13(sink) done
videoconvert13(src) link xvimagesink1(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
Add src probe done
Add sink probe done
Add src probe done
Add sink probe done
Previous change state from Stop to Play is failure
Ready to change state from Stop to Play
Change state from Stop to Play failed
Previous change state from Stop to Play is failure
Pipeline is in Stop state
pylonsrc0(src) unlink videoconvert0(sink) done.
Remove element pylonsrc0 from pipeine pipeline0
videoconvert0(src) unlink adtsrt1(sink) done.
Remove element videoconvert0 from pipeine pipeline0
videoconvert13(src) unlink xvimagesink1(sink) done.
Remove element xvimagesink1 from pipeine pipeline0
adtsrt1(src) unlink adtransclassifier1(sink) done.
Remove element adtsrt1 from pipeine pipeline0
adtransclassifier1(src) unlink adinferdraw0(sink) done.
Remove element adtransclassifier1 from pipeine pipeline0
adinferdraw0(src) unlink videoconvert13(sink) done.
Remove element adinferdraw0 from pipeine pipeline0
Remove element videoconvert13 from pipeine pipeline0
New pipeline pipeline1
Add element videoconvert0 into pipeline pipeline1
Add element xvimagesink1 into pipeline pipeline1
Add element adtsrt1 into pipeline pipeline1
Add element adinferdraw0 into pipeline pipeline1
Add element videoconvert13 into pipeline pipeline1
Add element pylonsrc5 into pipeline pipeline1
Add element adtransssd0 into pipeline pipeline1
videoconvert0(src) link adtsrt1(sink) done
adtsrt1(src) link adtransssd0(sink) done
adinferdraw0(src) link videoconvert13(sink) done
videoconvert13(src) link xvimagesink1(sink) done
pylonsrc5(src) link videoconvert0(sink) done
adtransssd0(src) link adinferdraw0(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
pylonsrc5(src) unlink videoconvert0(sink) done.
videoconvert0(src) unlink adtsrt1(sink) done.
Remove element videoconvert0 from pipeine pipeline1
videoconvert13(src) unlink xvimagesink1(sink) done.
Remove element xvimagesink1 from pipeine pipeline1
adtsrt1(src) unlink adtransssd0(sink) done.
Remove element adtsrt1 from pipeine pipeline1
adtransssd0(src) unlink adinferdraw0(sink) done.
adinferdraw0(src) unlink videoconvert13(sink) done.
Remove element adinferdraw0 from pipeine pipeline1
Remove element videoconvert13 from pipeine pipeline1
Remove element pylonsrc5 from pipeine pipeline1
Remove element adtransssd0 from pipeine pipeline1
New pipeline pipeline2
Add element videoconvert0 into pipeline pipeline2
Add element xvimagesink1 into pipeline pipeline2
Add element adtsrt1 into pipeline pipeline2
Add element adinferdraw0 into pipeline pipeline2
Add element videoconvert13 into pipeline pipeline2
Add element pylonsrc5 into pipeline pipeline2
Add element adtranslator0 into pipeline pipeline2
videoconvert0(src) link adtsrt1(sink) done
adtsrt1(src) link adtranslator0(sink) done
adinferdraw0(src) link videoconvert13(sink) done
videoconvert13(src) link xvimagesink1(sink) done
pylonsrc5(src) link videoconvert0(sink) done
adtranslator0(src) link adinferdraw0(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
pylonsrc5(src) unlink videoconvert0(sink) done.
videoconvert0(src) unlink adtsrt1(sink) done.
Remove element videoconvert0 from pipeine pipeline2
videoconvert13(src) unlink xvimagesink1(sink) done.
Remove element xvimagesink1 from pipeine pipeline2
adtsrt1(src) unlink adtranslator0(sink) done.
Remove element adtsrt1 from pipeine pipeline2
adtranslator0(src) unlink adinferdraw0(sink) done.
adinferdraw0(src) unlink videoconvert13(sink) done.
Remove element adinferdraw0 from pipeine pipeline2
Remove element videoconvert13 from pipeine pipeline2
Remove element pylonsrc5 from pipeine pipeline2
Remove element adtranslator0 from pipeine pipeline2
New pipeline pipeline3
Add element videoconvert0 into pipeline pipeline3
Add element xvimagesink1 into pipeline pipeline3
Add element adtsrt1 into pipeline pipeline3
Add element adinferdraw0 into pipeline pipeline3
Add element videoconvert13 into pipeline pipeline3
Add element adtrans_openpose+adtrans_openposepy1 into pipeline pipeline3
Add element pylonsrc5 into pipeline pipeline3
videoconvert0(src) link adtsrt1(sink) done
adtsrt1(src) link adtrans_openpose+adtrans_openposepy1(sink) done
adinferdraw0(src) link videoconvert13(sink) done
videoconvert13(src) link xvimagesink1(sink) done
adtrans_openpose+adtrans_openposepy1(src) link adinferdraw0(sink) done
pylonsrc5(src) link videoconvert0(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
pylonsrc5(src) unlink videoconvert0(sink) done.
videoconvert0(src) unlink adtsrt1(sink) done.
Remove element videoconvert0 from pipeine pipeline3
videoconvert13(src) unlink xvimagesink1(sink) done.
Remove element xvimagesink1 from pipeine pipeline3
adtsrt1(src) unlink adtrans_openpose+adtrans_openposepy1(sink) done.
Remove element adtsrt1 from pipeine pipeline3
adtrans_openpose+adtrans_openposepy1(src) unlink adinferdraw0(sink) done.
adinferdraw0(src) unlink videoconvert13(sink) done.
Remove element adinferdraw0 from pipeine pipeline3
Remove element videoconvert13 from pipeine pipeline3
Remove element adtrans_openpose+adtrans_openposepy1 from pipeine pipeline3
Remove element pylonsrc5 from pipeine pipeline3
New pipeline pipeline4
Add element filesrc into pipeline pipeline4
Add element decodebin into pipeline pipeline4
Add element videoconvert into pipeline pipeline4
Add element adrt into pipeline pipeline4
Add element adtrans_ssd into pipeline pipeline4
Add element videoconvert1 into pipeline pipeline4
Add element nvvideoconvert into pipeline pipeline4
Add element ximagesink into pipeline pipeline4
filesrc(src) link decodebin(sink) done
videoconvert(src) link adrt(sink) done
adrt(src) link adtrans_ssd(sink) done
videoconvert1(src) link ximagesink(sink) done
nvvideoconvert(src) link videoconvert(sink) done
{UUID('bca7b703-d761-4063-8c73-be4e47e9ecc7'): <class[filesrc]; name[filesrc]; graph[root]>, UUID('bde276fc-a764-42cc-a4f7-545353879424'): <class[decodebin]; name[decodebin]; graph[root]>, UUID('125768c3-6fdb-4b1b-8f6e-e4087ffb70b2'): <class[videoconvert]; name[videoconvert]; graph[root]>, UUID('9b8c0a35-5072-4e33-a908-25f2bf2c2a0e'): <class[adrt]; name[adrt]; graph[root]>, UUID('fd8980e4-2ea7-4c67-9a81-fc50bc199d9c'): <class[adtrans_ssd]; name[adtrans_ssd2]; graph[root]>, UUID('46f66a36-d7c2-4cdf-9717-1e8b1ef2df42'): <class[videoconvert]; name[videoconvert1]; graph[root]>, UUID('701813b1-602c-410e-b453-6d3425073ce5'): <class[nvvideoconvert]; name[nvvideoconvert]; graph[root]>, UUID('8e2d33cf-6c26-463b-b2a9-651b11ec49cf'): <class[ximagesink]; name[ximagesink]; graph[root]>} 1e9ff6b5-97f4-4213-9dc0-14320d881de8
Ready to change state from Stop to Play
Change state from Stop to Play failed
filesrc(src) unlink decodebin(sink) done.
Remove element filesrc from pipeine pipeline4
Remove the ghostpad handler from decodebin
Remove element decodebin from pipeine pipeline4
nvvideoconvert(src) unlink videoconvert(sink) done.
videoconvert(src) unlink adrt(sink) done.
Remove element videoconvert from pipeine pipeline4
adrt(src) unlink adtrans_ssd(sink) done.
Remove element adrt from pipeine pipeline4
Remove element adtrans_ssd from pipeine pipeline4
videoconvert1(src) unlink ximagesink(sink) done.
Remove element videoconvert1 from pipeine pipeline4
Remove element nvvideoconvert from pipeine pipeline4
Remove element ximagesink from pipeine pipeline4
New pipeline pipeline5
Add element videoconvert into pipeline pipeline5
Add element adrt into pipeline pipeline5
Add element adtrans_ssd into pipeline pipeline5
Add element videoconvert1 into pipeline pipeline5
Add element ximagesink into pipeline pipeline5
Add element pylonsrc0 into pipeline pipeline5
videoconvert(src) link adrt(sink) done
adrt(src) link adtrans_ssd(sink) done
videoconvert1(src) link ximagesink(sink) done
{UUID('125768c3-6fdb-4b1b-8f6e-e4087ffb70b2'): <class[videoconvert]; name[videoconvert]; graph[root]>, UUID('9b8c0a35-5072-4e33-a908-25f2bf2c2a0e'): <class[adrt]; name[adrt]; graph[root]>, UUID('fd8980e4-2ea7-4c67-9a81-fc50bc199d9c'): <class[adtrans_ssd]; name[adtrans_ssd2]; graph[root]>, UUID('46f66a36-d7c2-4cdf-9717-1e8b1ef2df42'): <class[videoconvert]; name[videoconvert1]; graph[root]>, UUID('8e2d33cf-6c26-463b-b2a9-651b11ec49cf'): <class[ximagesink]; name[ximagesink]; graph[root]>, UUID('05ba2bd1-af27-4903-ae7f-6408d8d9d503'): <class[pylonsrc]; name[pylonsrc]; graph[root]>} 1e9ff6b5-97f4-4213-9dc0-14320d881de8
pylonsrc0(src) link videoconvert(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
```

_Originally posted by @maratfaizov in https://github.com/IST-EVA-Support/EVA_Show-Case/issues/8#issuecomment-863343706_

**Comment by Moda-Lin** [comment]
Dear @maratfaizov ,
Sorry, I forgot to provide the engine file and the label file.
http://ftp.adlinktech.com/moda/EVA_IDE.zip
Please download EVA_IDE.zip and unzip this file on the desktop.
So that "EVA_IDE" folder will on NEON desktop.
There is many pygraph samples in this folder.

Best Regards
Moda Lin

**Comment by paul-adlink** [comment]
test
