### ISSUE TITLE
Errors during installation and running of example

### ISSUE THREAD

**Issue by maratfaizov** [IST-EVA-Support/EVA_Show-Case#8]
Hello,
I am having troubles getting these examples running.
I have got a NEON-202B-JNX Starter Kit and wanted to try the showcases.
First, I get a few errors, when I run the install.sh script:
```
adlink@dyn-163:~/Documents/EVA_Show-Case/src/demo/geofence$ ./install.sh 
ModelNetwork: ssd_mobilenet
=> Start installing...
=> Building geofence plugin...
=> check ./build folder...
=> ./build does not exist and will build it.
=> start to configure by meson...
The Meson build system
Version: 0.57.1
Source dir: /home/adlink/Documents/EVA_Show-Case/src/plugins/geofence
Build dir: /home/adlink/Documents/EVA_Show-Case/src/plugins/geofence/build
Build type: native build
Project name: GEO-Fencing
Project version: 1.0.0
C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the host machine: cc ld.bfd 2.30
Host machine cpu family: aarch64
Host machine cpu: aarch64
C++ compiler for the host machine: c++ (gcc 7.5.0 "c++ (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gstreamer-1.0 found: YES 1.14.5
Run-time dependency gstreamer-base-1.0 found: YES 1.14.5
Library gstvideo-1.0 found: YES
Library opencv_core found: YES
Library opencv_imgproc found: YES
Library opencv_video found: YES
Library opencv_videoio found: YES
Library opencv_imgcodecs found: YES
Library opencv_highgui found: YES

meson.build:30:2: ERROR: Include dir /usr/local/include/opencv4 does not exist.

A full log can be found at /home/adlink/Documents/EVA_Show-Case/src/plugins/geofence/build/meson-logs/meson-log.txt
=> start to compile by ninja...
ninja: Entering directory `/home/adlink/Documents/EVA_Show-Case/src/plugins/geofence/build'
ninja: error: loading 'build.ninja': No such file or directory
=> check eva plugings folder...
=> /opt/adlink/eva/plugins/libgeofence.so does not exist, will copy it
=> start copying to /opt/adlink/eva/plugins/ ......
[sudo] password for adlink: 
cp: cannot stat './build/libgeofence.so': No such file or directory
=> copy done
=> clear cache of gstreamer...
=> registry is clean.
=> Build plugin, geofence, process completed!
=> Demo video exists, skip.
=> Model exists, skip.
=> alert-def-area-geo.txt exists, skip.
=> adlink-mobilenetSSDv2-geo-fencing-label.txt exists, skip.
=> Deploy alert plugin...
=> check python plugings folder...
=> /opt/adlink/eva/plugins/python/emailAlert.py exist, will remove it first.
=> /opt/adlink/eva/plugins/python/emailAlert.py is removed.
=> Start to copy python email_alert plugin to eva plugins/python folder...
=> Copy done.
=> start re-source ......
Pylon environment initialized
=> Copy and re-source process completed!
=> check python plugings folder...
=> /opt/adlink/eva/plugins/python/voiceAlert.py exist, will remove it first.
=> /opt/adlink/eva/plugins/python/voiceAlert.py is removed.
=> Start to copy python voice_alert plugin to eva plugins/python folder...
=> Copy done.
=> start re-source ......
Pylon environment initialized
=> Copy and re-source process completed!
=> Install related python package
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: protobuf==3.3.0 in /home/adlink/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: numpy==1.19.4 in /home/adlink/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (1.19.4)
Requirement already satisfied: pyttsx3==2.90 in /home/adlink/.local/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (2.90)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf==3.3.0->-r requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: setuptools in /home/adlink/.local/lib/python3.6/site-packages (from protobuf==3.3.0->-r requirements.txt (line 1)) (54.2.0)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
espeak is already the newest version (1.48.04+dfsg-5).
The following packages were automatically installed and are no longer required:
  python3-click python3-colorama
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
=> Installation completed, you could run this demo by execute ./run.sh
```
Installation still gets completed. When I run the run.sh script, I get a warning, and then nothing happens:
```
adlink@dyn-163:~/Documents/EVA_Show-Case/src/demo/geofence$ ./run.sh 
=> Start running geofence demo...
WARNING: erroneous pipeline: no element "avdec_h264"
adlink@dyn-163:~/Documents/EVA_Show-Case/src/demo/geofence$ 
```
When I open EVA SDK, I get two other errors:
```
adlink@dyn-163:~/Documents/EVA_Show-Case/src/demo/geofence$ EVA_IDE 
ad_cameraflir_class_init called ... 
ad_camerahik_class_init called ... 
2021-06-07 23:39:16.381583: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "/home/adlink/adlink/eva/IDE/plugins/python/emailAlert.py", line 7, in <module>
    import smtplib
ModuleNotFoundError: No module named 'smtplib'
Traceback (most recent call last):
  File "/home/adlink/adlink/eva/IDE/plugins/python/voiceAlert.py", line 7, in <module>
    import pyttsx3
ModuleNotFoundError: No module named 'pyttsx3'
```
SDK still gets opened. When I load the showcase1, it seems incomplete: a few nodes for email notification are missing compared to the example screenshot in the demo-README.
![showcase1_incomplete](https://user-images.githubusercontent.com/6200087/121049549-5f4ba600-c7ea-11eb-943a-8255863f9038.png)
I guess it is because **smtplib** is missing. Are there any additional installation steps required before running these examples, but they are not listed in README?

Thank you!

**Comment by IST-EVA-Support** [comment]
Dear @maratfaizov ,

First, thanks for the feedback!
Second, which version of EVA you are using now?
Use the command below and tell us the version information
`cat /opt/adlink/eva/VERSION`
thank you!

**Comment by maratfaizov** [comment]
Dear @Moda-Lin ,

Thank you for your help.
The EVA version is 3.1.1. I followed all steps as you described, but the outcome is unfortunately absolutely identical: same errors, example does not work.

**Comment by Moda-Lin** [comment]
Dear @maratfaizov ,
I updated the source code, but I would like to ask you to inspect the elements first.
```
gst-inspect-1.0 geofence
gst-inspect-1.0 libav
gst-inspect-1.0 email_alert
gst-inspect-1.0 voice_alert
```
and please tell me which command will get "No such element or plugin".
After that, repeat steps 1 to 4 that I mentioned yesterday.


For EVA_IDE, it can't not execute email & voice alert now.
This feature will be updated in EVA_IDE in the future.

**Comment by Moda-Lin** [comment]
Dear @maratfaizov ,
Did it work?
If you encounter other problems, please also raise them.
Thank you.

**Comment by maratfaizov** [comment]
Dear @Moda-Lin 
Inspection of the elements showed that geofence and libav were missing. I repeated then steps 1 to 4 and these elements were added. ./install and ./run scripts work now as well. Thank you for your help!
However, my highest interest is to use the EVA IDE for inference. Those 2 showcases (geofence and weardetection) do not work in EVA, unfortunately. Are there any working examples for EVA IDE that use the NEON camera as a video source?

**Comment by Moda-Lin** [comment]
Dear @maratfaizov ,
The EVA IDE for inference can load from IDE_NEON.zip
[IDE_NEON.zip](https://github.com/IST-EVA-Support/EVA_Show-Case/files/6653535/IDE_NEON.zip)

This feature of email & voice alert  will be updated in the future. At that time, you can use 2 showcases in EVA IDE.

Best Regards
Moda Lin

**Comment by IST-EVA-Support** [comment]
@maratfaizov I will close this issue since the main topic is solved. If you still have any other problems, it is very welcome to create issues for asking more help! Thank you!

**Comment by maratfaizov** [comment]
Dear @Moda-Lin ,
Thank you for these examples for EVA IDE. Unfortunately, none of them work. When I click play button nothing happens in IDE. Here is the output in terminal after I start EVA IDE and then open and play each example one after another:
```
adlink@dyn-163:~$ EVA_IDE 
ad_cameraflir_class_init called ... 
ad_camerahik_class_init called ... 
2021-06-17 23:26:53.326652: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "/home/adlink/adlink/eva/IDE/plugins/python/emailAlert.py", line 7, in <module>
    import smtplib
ModuleNotFoundError: No module named 'smtplib'
Traceback (most recent call last):
  File "/home/adlink/adlink/eva/IDE/plugins/python/voiceAlert.py", line 7, in <module>
    import pyttsx3
ModuleNotFoundError: No module named 'pyttsx3'
New pipeline pipeline0
Add element pylonsrc0 into pipeline pipeline0
Add element videoconvert0 into pipeline pipeline0
Add element xvimagesink1 into pipeline pipeline0
Add element adtsrt1 into pipeline pipeline0
Add element adtransclassifier1 into pipeline pipeline0
Add element adinferdraw0 into pipeline pipeline0
Add element videoconvert13 into pipeline pipeline0
pylonsrc0(src) link videoconvert0(sink) done
videoconvert0(src) link adtsrt1(sink) done
adtsrt1(src) link adtransclassifier1(sink) done
adtransclassifier1(src) link adinferdraw0(sink) done
adinferdraw0(src) link videoconvert13(sink) done
videoconvert13(src) link xvimagesink1(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
Add src probe done
Add sink probe done
Add src probe done
Add sink probe done
Previous change state from Stop to Play is failure
Ready to change state from Stop to Play
Change state from Stop to Play failed
Previous change state from Stop to Play is failure
Pipeline is in Stop state
pylonsrc0(src) unlink videoconvert0(sink) done.
Remove element pylonsrc0 from pipeine pipeline0
videoconvert0(src) unlink adtsrt1(sink) done.
Remove element videoconvert0 from pipeine pipeline0
videoconvert13(src) unlink xvimagesink1(sink) done.
Remove element xvimagesink1 from pipeine pipeline0
adtsrt1(src) unlink adtransclassifier1(sink) done.
Remove element adtsrt1 from pipeine pipeline0
adtransclassifier1(src) unlink adinferdraw0(sink) done.
Remove element adtransclassifier1 from pipeine pipeline0
adinferdraw0(src) unlink videoconvert13(sink) done.
Remove element adinferdraw0 from pipeine pipeline0
Remove element videoconvert13 from pipeine pipeline0
New pipeline pipeline1
Add element videoconvert0 into pipeline pipeline1
Add element xvimagesink1 into pipeline pipeline1
Add element adtsrt1 into pipeline pipeline1
Add element adinferdraw0 into pipeline pipeline1
Add element videoconvert13 into pipeline pipeline1
Add element pylonsrc5 into pipeline pipeline1
Add element adtransssd0 into pipeline pipeline1
videoconvert0(src) link adtsrt1(sink) done
adtsrt1(src) link adtransssd0(sink) done
adinferdraw0(src) link videoconvert13(sink) done
videoconvert13(src) link xvimagesink1(sink) done
pylonsrc5(src) link videoconvert0(sink) done
adtransssd0(src) link adinferdraw0(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
pylonsrc5(src) unlink videoconvert0(sink) done.
videoconvert0(src) unlink adtsrt1(sink) done.
Remove element videoconvert0 from pipeine pipeline1
videoconvert13(src) unlink xvimagesink1(sink) done.
Remove element xvimagesink1 from pipeine pipeline1
adtsrt1(src) unlink adtransssd0(sink) done.
Remove element adtsrt1 from pipeine pipeline1
adtransssd0(src) unlink adinferdraw0(sink) done.
adinferdraw0(src) unlink videoconvert13(sink) done.
Remove element adinferdraw0 from pipeine pipeline1
Remove element videoconvert13 from pipeine pipeline1
Remove element pylonsrc5 from pipeine pipeline1
Remove element adtransssd0 from pipeine pipeline1
New pipeline pipeline2
Add element videoconvert0 into pipeline pipeline2
Add element xvimagesink1 into pipeline pipeline2
Add element adtsrt1 into pipeline pipeline2
Add element adinferdraw0 into pipeline pipeline2
Add element videoconvert13 into pipeline pipeline2
Add element pylonsrc5 into pipeline pipeline2
Add element adtranslator0 into pipeline pipeline2
videoconvert0(src) link adtsrt1(sink) done
adtsrt1(src) link adtranslator0(sink) done
adinferdraw0(src) link videoconvert13(sink) done
videoconvert13(src) link xvimagesink1(sink) done
pylonsrc5(src) link videoconvert0(sink) done
adtranslator0(src) link adinferdraw0(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
pylonsrc5(src) unlink videoconvert0(sink) done.
videoconvert0(src) unlink adtsrt1(sink) done.
Remove element videoconvert0 from pipeine pipeline2
videoconvert13(src) unlink xvimagesink1(sink) done.
Remove element xvimagesink1 from pipeine pipeline2
adtsrt1(src) unlink adtranslator0(sink) done.
Remove element adtsrt1 from pipeine pipeline2
adtranslator0(src) unlink adinferdraw0(sink) done.
adinferdraw0(src) unlink videoconvert13(sink) done.
Remove element adinferdraw0 from pipeine pipeline2
Remove element videoconvert13 from pipeine pipeline2
Remove element pylonsrc5 from pipeine pipeline2
Remove element adtranslator0 from pipeine pipeline2
New pipeline pipeline3
Add element videoconvert0 into pipeline pipeline3
Add element xvimagesink1 into pipeline pipeline3
Add element adtsrt1 into pipeline pipeline3
Add element adinferdraw0 into pipeline pipeline3
Add element videoconvert13 into pipeline pipeline3
Add element adtrans_openpose+adtrans_openposepy1 into pipeline pipeline3
Add element pylonsrc5 into pipeline pipeline3
videoconvert0(src) link adtsrt1(sink) done
adtsrt1(src) link adtrans_openpose+adtrans_openposepy1(sink) done
adinferdraw0(src) link videoconvert13(sink) done
videoconvert13(src) link xvimagesink1(sink) done
adtrans_openpose+adtrans_openposepy1(src) link adinferdraw0(sink) done
pylonsrc5(src) link videoconvert0(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
pylonsrc5(src) unlink videoconvert0(sink) done.
videoconvert0(src) unlink adtsrt1(sink) done.
Remove element videoconvert0 from pipeine pipeline3
videoconvert13(src) unlink xvimagesink1(sink) done.
Remove element xvimagesink1 from pipeine pipeline3
adtsrt1(src) unlink adtrans_openpose+adtrans_openposepy1(sink) done.
Remove element adtsrt1 from pipeine pipeline3
adtrans_openpose+adtrans_openposepy1(src) unlink adinferdraw0(sink) done.
adinferdraw0(src) unlink videoconvert13(sink) done.
Remove element adinferdraw0 from pipeine pipeline3
Remove element videoconvert13 from pipeine pipeline3
Remove element adtrans_openpose+adtrans_openposepy1 from pipeine pipeline3
Remove element pylonsrc5 from pipeine pipeline3
New pipeline pipeline4
Add element filesrc into pipeline pipeline4
Add element decodebin into pipeline pipeline4
Add element videoconvert into pipeline pipeline4
Add element adrt into pipeline pipeline4
Add element adtrans_ssd into pipeline pipeline4
Add element videoconvert1 into pipeline pipeline4
Add element nvvideoconvert into pipeline pipeline4
Add element ximagesink into pipeline pipeline4
filesrc(src) link decodebin(sink) done
videoconvert(src) link adrt(sink) done
adrt(src) link adtrans_ssd(sink) done
videoconvert1(src) link ximagesink(sink) done
nvvideoconvert(src) link videoconvert(sink) done
{UUID('bca7b703-d761-4063-8c73-be4e47e9ecc7'): <class[filesrc]; name[filesrc]; graph[root]>, UUID('bde276fc-a764-42cc-a4f7-545353879424'): <class[decodebin]; name[decodebin]; graph[root]>, UUID('125768c3-6fdb-4b1b-8f6e-e4087ffb70b2'): <class[videoconvert]; name[videoconvert]; graph[root]>, UUID('9b8c0a35-5072-4e33-a908-25f2bf2c2a0e'): <class[adrt]; name[adrt]; graph[root]>, UUID('fd8980e4-2ea7-4c67-9a81-fc50bc199d9c'): <class[adtrans_ssd]; name[adtrans_ssd2]; graph[root]>, UUID('46f66a36-d7c2-4cdf-9717-1e8b1ef2df42'): <class[videoconvert]; name[videoconvert1]; graph[root]>, UUID('701813b1-602c-410e-b453-6d3425073ce5'): <class[nvvideoconvert]; name[nvvideoconvert]; graph[root]>, UUID('8e2d33cf-6c26-463b-b2a9-651b11ec49cf'): <class[ximagesink]; name[ximagesink]; graph[root]>} 1e9ff6b5-97f4-4213-9dc0-14320d881de8
Ready to change state from Stop to Play
Change state from Stop to Play failed
filesrc(src) unlink decodebin(sink) done.
Remove element filesrc from pipeine pipeline4
Remove the ghostpad handler from decodebin
Remove element decodebin from pipeine pipeline4
nvvideoconvert(src) unlink videoconvert(sink) done.
videoconvert(src) unlink adrt(sink) done.
Remove element videoconvert from pipeine pipeline4
adrt(src) unlink adtrans_ssd(sink) done.
Remove element adrt from pipeine pipeline4
Remove element adtrans_ssd from pipeine pipeline4
videoconvert1(src) unlink ximagesink(sink) done.
Remove element videoconvert1 from pipeine pipeline4
Remove element nvvideoconvert from pipeine pipeline4
Remove element ximagesink from pipeine pipeline4
New pipeline pipeline5
Add element videoconvert into pipeline pipeline5
Add element adrt into pipeline pipeline5
Add element adtrans_ssd into pipeline pipeline5
Add element videoconvert1 into pipeline pipeline5
Add element ximagesink into pipeline pipeline5
Add element pylonsrc0 into pipeline pipeline5
videoconvert(src) link adrt(sink) done
adrt(src) link adtrans_ssd(sink) done
videoconvert1(src) link ximagesink(sink) done
{UUID('125768c3-6fdb-4b1b-8f6e-e4087ffb70b2'): <class[videoconvert]; name[videoconvert]; graph[root]>, UUID('9b8c0a35-5072-4e33-a908-25f2bf2c2a0e'): <class[adrt]; name[adrt]; graph[root]>, UUID('fd8980e4-2ea7-4c67-9a81-fc50bc199d9c'): <class[adtrans_ssd]; name[adtrans_ssd2]; graph[root]>, UUID('46f66a36-d7c2-4cdf-9717-1e8b1ef2df42'): <class[videoconvert]; name[videoconvert1]; graph[root]>, UUID('8e2d33cf-6c26-463b-b2a9-651b11ec49cf'): <class[ximagesink]; name[ximagesink]; graph[root]>, UUID('05ba2bd1-af27-4903-ae7f-6408d8d9d503'): <class[pylonsrc]; name[pylonsrc]; graph[root]>} 1e9ff6b5-97f4-4213-9dc0-14320d881de8
pylonsrc0(src) link videoconvert(sink) done
Ready to change state from Stop to Play
Change state from Stop to Play failed
```

**Comment by IST-EVA-Support** [comment]
Dear @maratfaizov and @Moda-Lin ,

Since this is another field of the issues. please move to #14 for further problem solving, thanks!

**Comment by Moda-Lin** [comment]
Dear @maratfaizov ,
Sorry, I forgot to provide the engine file and the label file.
http://ftp.adlinktech.com/moda/EVA_IDE.zip
Please download EVA_IDE.zip and unzip this file on the desktop.
So that "EVA_IDE" folder will on NEON desktop.
There is many pygraph samples in this folder.

Best Regards
Moda Lin

**Comment by Moda-Lin** [comment]
Dear @maratfaizov ,
Are there any other problems?
Thank you so much for your feedback.

Moda Lin

**Comment by maratfaizov** [comment]
Dear @Moda-Lin ,
Thank you very much for providing the examples. I have tried all of them and there is no more problems, everything works.

**Comment by IST-EVA-Support** [comment]
Dear @maratfaizov ,
Thanks for the feedback!
